import { notFound } from "next/navigation";
import { stringify as stringifyYaml } from "yaml";
import { getProposalStore } from "@/lib/proposals/singleton";
import { ProposalReviewer } from "./reviewer";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function ProposalDetailPage(
  { params }: PageProps,
): Promise<React.ReactElement> {
  const { id } = await params;
  const proposal = await getProposalStore().getProposal(id);
  if (!proposal) notFound();

  const proposedYaml = stringifyYaml(proposal.diff);
  // The "current" side of the diff is intentionally empty for v0: applied
  // ontology lives in YAML files generated by the apply pipeline (US-020).
  // Diffing against the on-disk ontology is a richer story; for now we
  // surface what the proposal adds, so reviewers see the full proposed
  // payload side-by-side with a placeholder for "what's already there".
  const currentYaml = "# current ontology snapshot not yet wired\n";

  return (
    <ProposalReviewer
      proposalId={proposal.id}
      sessionId={proposal.session_id}
      status={proposal.status}
      createdAt={proposal.created_at}
      impactedTables={proposal.diff.impacted_tables}
      currentYaml={currentYaml}
      proposedYaml={proposedYaml}
    />
  );
}
